### ISSUE TITLE
Automate build, test & deploy with Travis CI

### ISSUE THREAD

**Issue by billglover** [billglover/bbot#26]
The deployment and testing of BuddyBot is currently executed manually. We need to add Travis CI configuration to enable the automated test and deploy on commit. The following items should be considered:

**For branches:**
* confirm `go fmt`
* confirm `go vet`
* run tests
* if everything passes deploy to development instance

**For tagged releases:**
* confirm `go fmt`
* confirm `go vet`
* run tests
* update release notes on GitHub
* if everything passes deploy to production instance

Please discuss any additional features before adding support.

**Comment by dangarthwaite** [comment]
I've made an attempt at this: https://github.com/billglover/bbot/pull/31
I suggest splitting off "update release notes on GitHub" and "deploy to production" as different tasks.

**Comment by billglover** [comment]
Travis CI configuration now deploys to the following environments:
- development: on merge to master
- production: on tags
