### ISSUE TITLE
Add project level README file

### ISSUE THREAD

**Issue by billglover** [billglover/bbot#27]
The project does not currently have a README. Individual functions have their own README files but there is nothing that describes the project. Even a minimal README would be useful as it is the first thing people see when they visit the project.

**Comment by saideepd** [comment]
Hey @billglover would love to make a <strong>README</strong> for your <strong>BuddyBot</strong>. I would like to know it's uses and what problem it aims to solve.

**Comment by billglover** [comment]
Hi @saideepd, many thanks.

BuddyBot is a community minded Slack Bot. It allows people to flag Slack messages for possible Code of Conduct violation. When a message is flagged three things happen:

1. The user who flagged the message is notified that the report is being looked at.
2. The user who authored the message that has been flagged is notified and asked to review their message.
3. The team admins channel is notified that a message has been flagged, providing details of the message, the name of the reporter and a link to the message.

Other things to note:
* Further details are provided in README files for the individual functions. See `./cmd/*`.
* The bot has been built using the Serverless framework: https://serverless.com
* The bot has been designed to run on Amazon AWS Lambda
* The README should indicate that is persisted: access tokens. No messages, user data is stored.
* It currently only supports the CodeBuddies Slack workspace but multi workspace support is on the roadmap (see Milestones).

Any questions, I'll be happy to help.

**Comment by billglover** [comment]
@saideepd many thanks for the contribution, this has now been merged into master.

**Comment by saideepd** [comment]
@billglover You're welcome & thanks for the merge 👍
